const ADD_PRODUCT = "ADD_PRODUCT";
const DELETE_PRODUCT = "DELETE_PRODUCT";
const CLEAR_CART = "CLEAR_CART";
const INCREASE_QUANTITY = "INCREASE_QUANTITY";
const DECREASE_QUANTITY = "DECREASE_QUANTITY";

export {
  ADD_PRODUCT,
  DELETE_PRODUCT,
  CLEAR_CART,
  INCREASE_QUANTITY,
  DECREASE_QUANTITY,
};
